/**
 * Created by tolgahan on 04.11.2016.
 */
module.exports = {
    port: Symbol('port'),
    host: Symbol('host'),
    net: Symbol('net'),
    parent: Symbol('parent'),
    children: Symbol('children'),
    protocols: Symbol('protocols'),
    wrapped: Symbol('wrapped'),
    soprano: Symbol('soprano'),
    netEvents: Symbol('netEvents'),
    protocol: Symbol('protocol'),
    methods: Symbol('methods'),
    map: Symbol('map'),
    executor: Symbol('executor'),
    when: Symbol('when'),
    base: Symbol('base'),
    socketFactory: Symbol('socketFactory'),
    flags:Symbol('flags'),
    filterFactory: Symbol('filterFactory'),
    resources: Symbol('resources'),
    properties: Symbol('properties'),
    target: Symbol('target'),
    src: Symbol('src'),
    handlers: Symbol('handlers'),
    outputFilter: Symbol('outputFilter'),
    inputFilter: Symbol('inputFilter'),
    options: Symbol('options'),
    initialOptions: Symbol('initialOptions'),
    buffer: Symbol('buffer'),
    ready: Symbol('ready'),
    inputTransformer: Symbol('inputTransformer'),
    namespace: Symbol('namespace'),
    adapter: Symbol('adapter'),
    id: Symbol('id'),
    ids: Symbol('ids'),
    count: Symbol('count'),
    connected: Symbol('connected'),
    server: Symbol('server'),
    header: Symbol('header'),
    middlewares: Symbol('middlewares')
};